spring.application.name=taskflow
spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow
spring.datasource.username=postgres
spring.datasource.password=lola12
spring.jpa.hibernate.ddl-auto=validate