spring.application.name=Taskflow
spring.datasource.url=jdbc:postgresql://localhost:5433/Taskflow
spring.datasource.username=postgres
spring.datasource.password=lola12
spring.jpa.hibernate.ddl-auto=validate
server.port=8081